### ISSUE TITLE
Weapon Repair

### ISSUE THREAD

**Issue by Sebasflow23** [Arcanorum/dungeonz#165]
### Category
- Item 

### Feature description
Ability to repair things with durability by crafting it with a ore of it's kind on a anvil.

### Notes

From minecraft.

**Comment by Arcanorum** [comment]
I'm not a fan of these kinds of item repair suggestions, as they invalidate the whole idea of items being impermanent and eventually needing to be replaced with newer ones.
Why would you want to repair something instead of just making a new one?

Maybe if some of the design problems of it could be figured out, it could be offered as an option for certain kinds of guild specialities?
- What about items that have different kinds of materials? Which one should be used to do the repair?
- If it was the same amount of materials needed to repair, then how much total durability would be restored? Would it be % of max (restore 50%? restore to max?), or a fixed amount? If it was a % of max then it would be inconsistent as the base durability increases with crafting level. i.e. repairing a 100 max durability item for 50% would restore 50, but repairing a 150 max durability item would restore 75, so the base max durability makes a difference.

**Comment by Sebasflow23** [comment]
> What about items that have different kinds of materials? Which one should be used to do the repair?

For example Oak Bow, it would use the material that it used the most of. In this case Oak.

> If it was the same amount of materials needed to repair, then how much total durability would be restored? Would it be % of max (restore 50%? restore to max?), or a fixed amount? If it was a % of max then it would be inconsistent as the base durability increases with crafting level. i.e. repairing a 100 max durability item for 50% would restore 50, but repairing a 150 max durability item would restore 75, so the base max durability makes a difference.

That would depend on your armory or that other skill level, if you were level 50 then 50%.

**Comment by Arcanorum** [comment]
Closing as there is already more items being produced than are being used by players, to the point that many items just end up getting dropped to free up space. I think being able to repair things would only make this worse, or would be pointless if making a new item from scratch with 100% durability would easy anyway.
