### ISSUE TITLE
Add close tab confirmation, Ctrl + W, close button

### ISSUE THREAD

**Issue by Arcanorum** [Arcanorum/dungeonz#52]
A prompt when the user goes to close the tab that will confirm if they meant to do that, to avoid accidental misclick closing the game, and should inform them that they can create an account if they haven't done so already.

**AC:** If the user is not playing with an account, the "Create account" panel should be shown when a user event tries to close the page (x button, ctrl + W)

**Comment by coder-tim** [comment]
I did some investigation and found that this can be resolved by using the `onbeforeunload` event to display a pop up message when the player attempts to refresh the page or close the tab.

However, it seems like most modern browsers have disabled custom pop up messages in order to prevent spoofing attacks:

- https://stackoverflow.com/questions/38879742/is-it-possible-to-display-a-custom-message-in-the-beforeunload-popup 

- https://stackoverflow.com/questions/37782104/javascript-onbeforeunload-not-showing-custom-message

**Comment by Arcanorum** [comment]
If possible, it might be an alternative to just show the create account panel on the `onbeforeunload` event, as if they had pressed on the top right button directly. The message content doesn't necessarily need to be within the browser's own close confirmation box.

![image](https://user-images.githubusercontent.com/9785268/101554499-a9c0a700-39ae-11eb-8f14-29e32ebe4e5c.png)

ACs updated.
